apiVersion: v1
kind: Pod
metadata:
  name: liveness-exec-pod
  labels:
    test: liveness
spec:
  containers:
  - name: liveness
    image: centos:7
    command: ["/bin/sh", "-c", "echo ok > /tmp/health; sleep 60; rm -rf /tmp/health; sleep 60"]
    livenessProbe:
      exec:
        command: ["test", "-e", "/tmp/health"]
      initialDelaySeconds: 5
      periodSeconds: 10