apiVersion: v1
kind: Pod
metadata:
  name: readiness-exec-pod
  labels:
    test: readiness
spec:
  containers:
  - name: readiness
    image: centos:7
    command: ["/bin/sh", "-c", "echo ok > /tmp/ready; sleep 60; rm -rf /tmp/ready; sleep 60"]
    readinessProbe:
      exec:
        command: ["cat", "/tmp/ready"]
      initialDelaySeconds: 5
      periodSeconds: 10
