apiVersion: v1
kind: Service
metadata:
  name: nginx-node-port         # Service 的名称
  labels:
    name: nginx-node-port       # Service 的标签
spec:
  type: NodePort
  selector:                     # Service 选择器
    name: nginx                 # Service 选择器 必须 和 pod 标签一致 (key value 都必须一致, 否则 service 无法代理 pod)
  ports:
  - name: http
    port: 80                    # service 针对内部请求监听的端口
    targetPort: 80              # pod 应用的端口
    protocol: TCP
