apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx-scale                # replication controller 的名称
  labels:
    name: nginx-scale              # replication controller 的标签
spec:
  replicas: 1
  selector:                        # replication controller 选择器
    name: nginx-scale              # replication controller 选择器 必须 和 pod 标签一致 (key value 都必须一致, 否则报错)
  template:
    metadata:
      labels:
        name: nginx-scale          # 所有副本 pod 的标签, 上面的 selector 和 这里进行关联!
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80