apiVersion: v1
kind: PodTemplate
metadata:
  name: nginx-template
template:
  metadata:
    labels:
      app: nginx-template
  spec:
    containers:
    - name: nginx
      image: nginx
      ports:
      - containerPort: 80