apiVersion: v1
kind: Pod
metadata:
  name: hello-world
spec:
  restartPolicy: Never
  containers:
  - name: write
    image: centos:7
    command: ["/bin/sh", "-c", "echo \"Hello World\" >> /data/hello"]
    volumeMounts:
    - name: data
      mountPath: /data
  - name: hello
    image: centos:7
    command: ["bash", "-c", "sleep 10; cat /data/hello"]
    volumeMounts:
      - name: data
        mountPath: /data
  volumes:
  - name: data
    hostPath:
      path: /data