apiVersion: v1
kind: Pod
metadata:
  name: log-pod
spec:
  restartPolicy: OnFailure
  containers:
  - name: container1
    image: centos:7
    command:
    - /bin/sh
    -  -c
    - "echo \"container1: `date --rfc-3339 ns `\"; exit 0"
  - name: container2
    image: centos:7
    command:
    - /bin/sh
    -  -c
    - "echo \"container2: `date --rfc-3339 ns `\"; exit 0"