apiVersion: v1
kind: Pod
metadata:
  name: nginx-network-host
spec:
  containers:
  - name: nginx-network-host
    image: nginx
    ports:
    - name: web
      containerPort: 80
      protocol: TCP
  hostNetwork: true