apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: myapp-pod
    version: v1
spec:
  containers:
  - name: myapp
    image: centos:7
    command:
      ["/bin/sh", "-c", "echo username: ${USERNAME}, password: ${PASSWORD}", "sleep 3600"]
    env:
    - name: USERNAME
      valueFrom:
        configMapKeyRef:
          name: special-config
          key: username
    - name: PASSWORD
      valueFrom:
        configMapKeyRef:
          name: special-config
          key: password