apiVersion: v1
kind: Pod
metadata:
  name: secret-service-account-pod
spec:
  restartPolicy: OnFailure
  containers:
    - name: secret-service-account-pod
      image: centos:7
      command: ["/bin/sh", "-c", "while true; do sleep 5; done"]