apiVersion: v1
kind: Pod
metadata:
  name: emptydir-pod
  labels:
    app: emptydir-pod
    version: v1
spec:
  containers:
  - name: centos1
    image: centos:7
    command: ["/bin/sh", "-c", "while true; do sleep 5; done"]
    volumeMounts:
    - name: cache-volume
      mountPath: /cache           # 挂载在容器中的位置
  - name: centos2
    image: centos:7
    command: ["/bin/sh", "-c", "while true; do sleep 5; done"]
    volumeMounts:
    - name: cache-volume
      mountPath: /test            # 挂载在容器中的位置
  volumes:
  - name: cache-volume
    emptyDir: {}                  # emptyDir