apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    name: frontend
spec:
  type: NodePort
  ports:
  - port: 80            # Service 针对内部请求监听的端口
    nodePort: 31505     # 外部请求的监听端口
    targetPort: 80      # Pod 应用的端口
  selector:
    name: frontend