apiVersion: v1
kind: Service
metadata:
  name: mine-nginx        # Service 的名称
  labels:
    name: mine-nginx      # Service 的标签
spec:
  selector:               # Service 选择器
    name: mine-nginx      # Service 选择器 必须 和 pod 标签一致 (key value 都必须一致, 否则 service 无法代理 pod)
  ports:
  - port: 80              # Service 针对内部请求监听的端口
    targetPort: 80        # pod 应用的端口
    protocol: TCP