apiVersion: v1
kind: Service
metadata:
  name: mysql           # Service 的名称
  labels:
    name: mysql         # Service 的标签
spec:
  ports:
  - port: 3306          # Service 针对内部请求监听的端口
    targetPort: 3306    # Pod 应用的端口
    protocol: TCP